# JAN 2025
name: Update Tree File Workflow
on: workflow_dispatch
jobs:
  treeupdate:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Update tree
      run: |
        echo "Tree of files last updated on" > README.txt
        date >> README.txt
        tree >> README.txt
    - name: git commands
      run: |
        git config --global user.email "antares.minos@gmail.com"
        git config --global user.name "jorge-antares"
        git add *
        git commit -m "Updated using workflow treeupdate.yml"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
