# JAN 2025
name: Update Tree File Workflow
on: workflow_dispatch
jobs:
  treeupdate:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Update tree
      run: |
        echo "Tree of files last updated on" > README.md
        tree >> README.md
    - name: git commands
      run: |
        git add *
        git commit -m "Updated using workflow treeupdate.yml"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
